### ISSUE TITLE
Arcade city app is still keeping my private key and updating my meta data even after I have logged out of it

### ISSUE THREAD

**Issue by vishalxl** [ArcadeCity/app#22]
An example is event id: 9895464a03452b342546a0b67a966f6cdbf62e1b15ad140b36cf3e4ae687629c

Which was made a day after I had logged out of Arcade City. 

This means 

a) Arcade city is still keeping my private key, which it should not do. 

b) Arcade city is updating my information, which it should not do because I did not initiate that. 

the part (a) is more critical here. Arcade city app should not keep the private key once the user has logged out.

**Comment by vishalxl** [comment]
I uninstalled arcade city app a few hours ago, and it just sent another type 0 event using my pubkey: 53ad57710ab76474301150a8071fdbe93e1e3acaa6be2b879a4c7aa7e7ce9a8e

Means its still keeping my private key, which it should not be doing.

**Comment by vishalxl** [comment]
Update: It's likely that some other app which I am using is rebroadcasting the kind-0 events, and its not Arcade City doing it.

**Comment by vishalxl** [comment]
Just did a refresh on Anigma, and at that same instant this event was broadcast: ee1bdbfc775172c3fd1d98b7e161af9cf63131209851d1a8e0786d239cfd76a2

So almost certainly its anigma.io rebraodcasting events, and not Arcade City doing it. Closing the issue as #wrong issue.

**Comment by AtlanteanOne** [comment]
Thank you for the report and the clarification!

To clarify for everyone:
- Keys you enter into the AC app are stored only on your local encrypted device storage via [expo-secure-store](https://docs.expo.dev/versions/latest/sdk/securestore/) - and accessible only to the AC app
- Private keys are never sent anywhere, as you can verify in the code
- This app doesn't currently have a backend at all - it uses the Damus relay only
